plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Enabled: true
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "bin/**/*"
    - "exe/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "data/**/*"
    - "*.gem"
    - "Gemfile.lock"
    # Ad-hoc scripts not part of library or specs
    - "test_*.rb"
    - "script/**/*"

# String literals
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# BigDecimal-friendly configurations
Style/NumericLiterals:
  MinDigits: 4

# Disable cops that conflict with BigDecimal usage
Style/FloatDivision:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

# Performance cops that work well with BigDecimal
Performance/BigDecimalWithNumericArgument:
  Enabled: true

# RSpec configuration
RSpec/NestedGroups:
  Max: 4

# Relax RSpec cops that require significant refactors without behavioral gain
RSpec/InstanceVariable:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/RemoveConst:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/IdenticalEqualityAssertion:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false
RSpec/ExpectActual:
  Enabled: false

# Layout
Layout/LineLength:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true
Layout/BlockAlignment:
  Enabled: false

# Metrics
Metrics/AbcSize:
  Enabled: true
  Max: 20

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 10

Metrics/MethodLength:
  Enabled: true
  Max: 20

Metrics/BlockLength:
  Enabled: true
  Max: 30

Metrics/BlockNesting:
  Enabled: true
  Max: 4

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 10

Metrics/ClassLength:
  Enabled: true
  Max: 200

Metrics/ModuleLength:
  Enabled: true
  Max: 200

Metrics/ParameterLists:
  Enabled: true
  Max: 5

# Lint
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Lint/UnusedBlockArgument:
  AllowUnusedKeywordArguments: true

Lint/RedundantSafeNavigation:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/AmbiguousRange:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/NonLocalExitFromIterator:
  Enabled: true

Lint/SuppressedException:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
Lint/FloatComparison:
  Enabled: true
Lint/RescueException:
  Enabled: true
Lint/UnderscorePrefixedVariableName:
  Enabled: true

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GuardClause:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantReturn:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/RescueModifier:
  Enabled: true

Style/SafeNavigation:
  Enabled: false

Style/Semicolon:
  Enabled: true

Style/SingleLineMethods:
  Enabled: true

Style/StderrPuts:
  Enabled: true

Style/StringHashKeys:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/RedundantCapitalW:
  Enabled: true

Style/RedundantCondition:
  Enabled: true

Style/RedundantInterpolation:
  Enabled: false

Style/RedundantPercentQ:
  Enabled: true

Style/VariableInterpolation:
  Enabled: true

Style/WhenThen:
  Enabled: true

Style/WhileUntilModifier:
  Enabled: true

Style/WordArray:
  Enabled: true

# Relax style cops that are largely preference and may risk subtle behavior
Style/NumericPredicate:
  Enabled: true

Style/IdenticalConditionalBranches:
  Enabled: true

Style/MultilineBlockChain:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: true

Style/ComparableBetween:
  Enabled: true

Style/MinMaxComparison:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/DoubleNegation:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SymbolProc:
  Enabled: true

Style/ItAssignment:
  Enabled: true

# Naming
Naming/AccessorMethodName:
  Enabled: true

Naming/MethodParameterName:
  Enabled: true

Naming/PredicateMethod:
  Enabled: true

Naming/VariableNumber:
  Enabled: true

Naming/MemoizedInstanceVariableName:
  Enabled: true

Naming/PredicatePrefix:
  Enabled: true

# Performance
Performance/UnfreezeString:
  Enabled: true

Performance/UriDefaultParser:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/StringReplacement:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/RedundantBlockCall:
  Enabled: true

Performance/RedundantMatch:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseEach:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/Sum:
  Enabled: true

# Relax performance cops that require refactors
Performance/CollectionLiteralInLoop:
  Enabled: true

Performance/MapCompact:
  Enabled: true

Performance/RedundantEqualityComparisonBlock:
  Enabled: true

# Gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false
