plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Enabled: true
  NewCops: enable
  TargetRubyVersion: 3.2
  # Exclude:
  #   - "bin/**/*"
  #   - "exe/**/*"
  #   - "vendor/**/*"
  #   - "tmp/**/*"
  #   - "data/**/*"
  #   - "*.gem"
  #   - "Gemfile.lock"
  #   # Ad-hoc scripts not part of library or specs
  #   - "test_*.rb"
  #   - "script/**/*"