# frozen_string_literal: true

require "dhan_scalper/version"
require "dhan_scalper/config"
require "dhan_scalper/indicators"

require "dhan_scalper/candle"
require "dhan_scalper/candle_series"
require "dhan_scalper/support/application_service"
require "dhan_scalper/support/time_zone"
require "dhan_scalper/support/money"
require "dhan_scalper/services/atomic_operations"
require "dhan_scalper/services/equity_calculator"
require "dhan_scalper/services/mtm_refresh_service"
require "dhan_scalper/atomic"
require "dhan_scalper/indicators/supertrend"
require "dhan_scalper/indicators/holy_grail"
require "dhan_scalper/trend_engine"
require "dhan_scalper/trend_enhanced"
require "dhan_scalper/order"
require "dhan_scalper/option_picker"
require "dhan_scalper/tick_cache"
require "dhan_scalper/trader"
require "dhan_scalper/app"
require "dhan_scalper/dryrun_app"
require "dhan_scalper/paper_app"
require "dhan_scalper/cli"
require "dhan_scalper/virtual_data_manager"
require "dhan_scalper/position"
require "dhan_scalper/quantity_sizer"
require "dhan_scalper/balance_providers/base"
require "dhan_scalper/balance_providers/paper_wallet"
require "dhan_scalper/balance_providers/live_balance"
require "dhan_scalper/csv_master"
require "dhan_scalper/brokers/base"
require "dhan_scalper/brokers/paper_broker"
require "dhan_scalper/brokers/dhan_broker"
require "dhan_scalper/state"
require "dhan_scalper/pnl"
# UI components removed - using simple console output instead
require "dhan_scalper/services/dhanhq_config"
require "dhan_scalper/services/market_feed"
require "dhan_scalper/services/websocket_cleanup"
require "dhan_scalper/services/rate_limiter"
require "dhan_scalper/services/historical_data_cache"
require "dhan_scalper/services/websocket_manager"
require "dhan_scalper/services/ltp_fallback"
require "dhan_scalper/services/order_monitor"
require "dhan_scalper/services/position_reconciler"
require "dhan_scalper/services/paper_position_tracker"
require "dhan_scalper/risk_manager"
require "dhan_scalper/ohlc_fetcher"
require "dhan_scalper/enhanced_position_tracker"
require "dhan_scalper/session_reporter"
require "dhan_scalper/headless_app"
require "dhan_scalper/enhanced_app"

# Stores
require "dhan_scalper/stores/redis_store"
require "dhan_scalper/stores/paper_reporter"

# Enhanced components
require "dhan_scalper/analyzers/position_analyzer"
require "dhan_scalper/risk/no_loss_trend_rider"
require "dhan_scalper/managers/entry_manager"
require "dhan_scalper/managers/exit_manager"
require "dhan_scalper/guards/session_guard"
require "dhan_scalper/notifications/telegram_notifier"
require "dhan_scalper/cache/redis_adapter"
require "dhan_scalper/cache/memory_adapter"

require "ruby-technical-analysis"
require "technical-analysis"

module DhanScalper
  # Register global WebSocket cleanup handlers
  Services::WebSocketCleanup.register_cleanup
end
