symbols: ["NIFTY"] # Test with NIFTY only in development

global:
  min_profit_target: 1000 # session target (₹)
  max_day_loss: 1500 # cutoff (₹)
  charge_per_order: 20 # flat per order (entry & exit both)
  allocation_pct: 0.30 # 30% of available balance per new position
  slippage_buffer_pct: 0.01 # cushion for sizing on premium
  max_lots_per_trade: 2 # Reduced for development testing
  decision_interval: 30 # seconds between signal checks (increased for dev)
  tp_pct: 0.35 # take profit
  sl_pct: 0.18 # stop loss
  trail_pct: 0.12 # trailing trigger %
  log_level: "DEBUG" # Set to DEBUG for development

paper:
  starting_balance: 100000 # Reduced paper wallet starting cash for testing

SYMBOLS:
  NIFTY:
    idx_sid: "13"
    seg_idx: "IDX_I"
    seg_opt: "NSE_FNO"
    strike_step: 50
    lot_size: 75 # verify with your master
    qty_multiplier: 1 # acts as per-symbol cap
    expiry_wday: 4 # Thu (fallback only - API expiry dates are used primarily)