symbols: ["NIFTY"]   # later: ["NIFTY","BANKNIFTY","SENSEX"]

global:
  min_profit_target: 1000
  max_day_loss: 1500
  charge_per_order: 20
  decision_interval: 10
  log_level: "INFO"
  tp_pct: 0.35
  sl_pct: 0.18
  trail_pct: 0.12

SYMBOLS:
  NIFTY:
    idx_sid: "13"
    seg_idx: "IDX_I"
    seg_opt: "NSE_FNO"
    strike_step: 50
    lot_size: 75
    qty_multiplier: 1
    expiry_wday: 4   # Thu
