symbols: ["NIFTY"] # later: ["NIFTY","BANKNIFTY","SENSEX"]

global:
  min_profit_target: 1000 # session target (₹)
  max_day_loss: 5000 # cutoff (₹)
  charge_per_order: 20 # flat per order (entry & exit both)
  allocation_pct: 0.30 # 30% of available balance per new position
  slippage_buffer_pct: 0.01 # cushion for sizing on premium
  max_lots_per_trade: 10
  decision_interval: 10 # seconds between signal checks
  tp_pct: 0.35 # take profit
  sl_pct: 0.18 # stop loss
  trail_pct: 0.12 # trailing trigger %
  log_level: "INFO"
  use_multi_timeframe: false # true for 1m+3m/5m, false for 1m only
  secondary_timeframe: 5 # 3 or 5 minutes for secondary timeframe
  min_premium_price: 1.0 # minimum premium price to avoid very low value orders

  # Headless bot specific settings
  min_signal_strength: 0.6 # minimum signal strength to execute trades (0.0-1.0)
  max_positions: 5 # maximum number of open positions
  risk_check_interval: 1 # seconds between risk management checks
  ohlc_fetch_interval: 180 # seconds between OHLC data fetches (3 minutes)
  ohlc_timeframes: ["1", "5"] # timeframes to fetch OHLC data for

paper:
  starting_balance: 200000 # paper wallet starting cash

SYMBOLS:
  NIFTY:
    idx_sid: "13"
    seg_idx: "IDX_I"
    seg_opt: "NSE_FNO"
    strike_step: 50
    lot_size: 75 # verify with your master
    qty_multiplier: 1 # acts as per-symbol cap
    expiry_wday: 4 # Thu (fallback only - API expiry dates are used primarily)
