symbols: ["NIFTY", "BANKNIFTY", "SENSEX"]

global:
  session_hours: ["09:20", "15:25"]
  min_profit_target: 1000 # session target (₹)
  max_day_loss: 1500 # cutoff (₹)
  charge_per_order: 20 # flat per order (entry & exit both)
  allocation_pct: 0.30 # 30% of available balance per new position
  slippage_buffer_pct: 0.01 # cushion for sizing on premium
  max_lots_per_trade: 10
  decision_interval: 10 # seconds between signal checks
  # new structured intervals
  decision_interval_sec: 60 # run strategy once per minute per symbol
  risk_loop_interval_sec: 1 # manage SL/TP/Trail each second
  ohlc_poll_minutes: 3 # pull minute OHLC every 3 mins
  log_throttle_sec: 60 # per component throttling
  redis_namespace: "dhan_scalper:v1"
  historical_stagger_sec: 4 # spread requests per symbol
  tp_pct: 0.35 # take profit
  sl_pct: 0.18 # stop loss
  trail_pct: 0.12 # trailing trigger %

  # Enhanced Risk Management
  time_stop_seconds: 300 # close position after 5 minutes
  enable_time_stop: true
  max_daily_loss_rs: 2000.0 # maximum daily loss in ₹
  enable_daily_loss_cap: true
  cooldown_after_loss_seconds: 180 # 3 minutes cooldown after loss
  enable_cooldown: true
  log_level: "INFO"
  use_multi_timeframe: false # true for 1m+3m/5m, false for 1m only
  secondary_timeframe: 5 # 3 or 5 minutes for secondary timeframe
  min_premium_price: 1.0 # minimum premium price to avoid very low value orders
  log_status_every: 60 # seconds

  # Headless bot specific settings
  min_signal_strength: 0.6 # minimum signal strength to execute trades (0.0-1.0)
  max_positions: 5 # maximum number of open positions
  risk_check_interval: 1 # seconds between risk management checks
  ohlc_fetch_interval: 180 # seconds between OHLC data fetches (3 minutes)
  ohlc_timeframes: ["1", "5"] # timeframes to fetch OHLC data for

paper:
  starting_balance: 200000 # paper wallet starting cash

SYMBOLS:
  NIFTY:
    idx_sid: "13"
    seg_idx: "IDX_I"
    seg_opt: "NSE_FNO"
    strike_step: 50
    lot_size: 75 # verify with your master
    qty_multiplier: 1 # acts as per-symbol cap
    expiry_wday: 4 # Thu (fallback only - API expiry dates are used primarily)

  BANKNIFTY:
    idx_sid: "25"
    seg_idx: "IDX_I"
    seg_opt: "NSE_FNO"
    strike_step: 100
    lot_size: 35 # verify with your master
    qty_multiplier: 1 # acts as per-symbol cap
    expiry_wday: 4 # Thu (fallback only - API expiry dates are used primarily)

  SENSEX:
    idx_sid: "51"
    seg_idx: "IDX_I"
    seg_opt: "BSE_FNO"
    strike_step: 100
    lot_size: 20 # verify with your master
    qty_multiplier: 1 # acts as per-symbol cap
    expiry_wday: 4 # Thu (fallback only - API expiry dates are used primarily)
