#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  require 'bundler/setup'
rescue LoadError
  nil
end
begin
  require 'dotenv/load'
rescue LoadError
  nil
end
require 'dhan_scalper'
DhanScalper::CLI.start(ARGV)
